name: delman
description: An application for couriers
publish_to: 'none'
version: 1.5.10+46

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.2
  dio: ^4.0.0
  device_info_plus: ^1.0.1
  stack_trace: ^1.10.0
  # https://github.com/zubairehman/Flogs/issues/51
  f_logs:
    git:
      url: git://github.com/draganjovanovic1/Flogs
  fk_user_agent: ^2.0.1
  pub_semver: ^2.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0
  path_provider: ^2.0.2
  package_info: ^2.0.2
  sentry_flutter: ^6.2.2
  url_launcher: ^6.0.6
  location: ^4.1.1
  flutter_bloc: ^8.0.0
  yandex_mapkit:
    git:
      url: git://github.com/Unact/yandex_mapkit
  flutter_blue: ^0.8.0
  flutter_signature_pad: ^3.0.0
  iboxpro_flutter: ^1.0.1
  flutter_bluetooth_serial: ^0.3.2
  quiver: ^3.0.1
  qr_code_scanner: ^0.5.2
  permission_handler: ^8.1.4
  drift: ^1.1.1
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0

dev_dependencies:
  drift_dev: ^1.1.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
