name: delman
description: An application for couriers
publish_to: 'none'
version: 1.3.0+26

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.2
  dio: ^4.0.0
  device_info_plus: ^1.0.1
  stack_trace: ^1.10.0
  # https://github.com/zubairehman/Flogs/issues/51
  f_logs:
    git:
      url: git://github.com/draganjovanovic1/Flogs
  fk_user_agent: ^2.0.1
  pub_semver: ^2.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0
  path_provider: ^2.0.2
  package_info: ^2.0.2
  sentry_flutter: ^5.0.0
  provider: ^5.0.0
  url_launcher: ^6.0.6
  location: ^4.1.1
  yandex_mapkit: ^1.0.0
  flutter_blue: ^0.8.0
  flutter_signature_pad: ^3.0.0
  iboxpro_flutter: ^1.0.0
  # https://github.com/edufolly/flutter_bluetooth_serial/pull/122
  flutter_bluetooth_serial:
    git:
      url: git://github.com/fabiomarini/flutter_bluetooth_serial

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/app/data/schema.sql
    - lib/app/assets/images/placeicon.png
    - .env
